version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - containedctx
    - contextcheck
    - durationcheck
    - errcheck
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - mnd
    - noctx
    - perfsprint
    - protogetter
    - revive
    - sloglint
    - spancheck
    - staticcheck
    - unused
    - whitespace
  settings:
    exhaustive:
      check:
        - switch
        - map
      default-signifies-exhaustive: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
severity:
  default: error
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
