name: Build Test

on:
  pull_request:
    paths:
      - "**.go"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Test Builds
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.24"
          cache: false

      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Setup deps
        run: make setup

      - name: Go Mod hygine
        run: |
          go clean -modcache
          go mod tidy

      - name: Build
        run: make build

      - name: Test
        run: make test
