name: Build Test

on:
  pull_request:
    paths:
      - "**.go"
  workflow_dispatch:

jobs:
  build:
    name: Test Builds
    strategy:
      matrix:
        go-version: [1.22.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Setup deps
        run: make setup

      - name: Go Mod hygine
        run: |
          go clean -modcache
          go mod tidy

      - name: Build
        run: make build

      - name: Test
        run: make test
