name: Lint report

on:
  pull_request:
    paths:
      - "**.go"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  golangci-lint:
    name: Lint (golangci-lint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          cache: false
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
