name: Release Binaries

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          cache: false

      - uses: goreleaser/goreleaser-action@v4
        with:
          args: "release --clean"
          version: latest
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
